default:
  workspace: shared

stages:
- Build
- Test

jobs:
- name: Run tests
  stage: Build
  image: alpine
  services:
  - redis:alpine
  script:
  - echo Hello
  - composer -v

- name: Sleep
  stage: Build
  image: alpine
  script:
  - sleep 10

- name: Wake up
  stage: Build
  image: alpine
  workspace: none
  script:
  - echo Hello
  when: manual

- name: Sleep again
  stage: Build
  image: alpine
  script:
  - composer -v

- name: Sleep more
  stage: Test
  image: alpine
  script:
  - composer -v

- name: Say bye!
  stage: Test
  image: alpine
  script:
  - composer -v
  - echo Byeeee!
  
- name: Say bye again!
  stage: Test
  image: alpine
  workspace: none
  script:
  - echo Byeeeeeeee!
  - echo yeahhhhh!
