stages:
  - test

jobs:
  - name: test_result
    stage: test
    script:
      - echo test slack
    image: alpine
    test_result:
      type: junit
      path: coverage/junit.xml
    coverage:
      type: clover
      path: coverage/coverage.xml
    artifacts:
      name: artifacts
      paths:
      - coverage
      expires_in: 3 days
