stages:
  - test

jobs:
  - name: test_result
    stage: test
    script:
      - echo ok
    image: alpine
    test_result:
      type: junit
      path: coverage/junit.xml
    artifacts:
      paths:
      - coverage
      expires_in: 3 days
