default:
  only:
    events:
      - pull_request

workspace: true

stages:
- Build
- Test

jobs:
- name: Run tests
  stage: Build
  image: alpine
  script:
  - echo OKK

- name: Run tests other
  stage: Build
  image: alpine
  script:
  - echo OKK
