default:
  workspace: shared

stages:
- Build
- Test

jobs:
- name: Run tests
  stage: Build
  image: alpine
  script:
  - echo OK
- name: Run tests other
  stage: Build
  image: alpine
  script:
  - echo OK!
